### ISSUE TITLE
printing with CircuitPython Kernel

### ISSUE THREAD

**Issue by Arukaito** [adafruit/circuitpython_kernel#20]
* CircuitPython Kernel version: 0.3.2 - Adafruit Metro Express M0 - SAMD
* Python version:3.6
* Operating System: Windows 10 - Anaconda

### Description

Im trying to use `print()` in Jupyterlab with CircuitPython Kernel
when i delete completely `while True:` it prints alright but when im in a loop it just doesnt work.
CircuitPython Kernel is not able to do this?
even the command line is not showing my prints im doing something wrong or this is not supported?

I can read print() in a while loop with MU 
do i need to attach an external debugger? 

Sorry about my english, is not my native language

### What I Did

`import digitalio
from board import *
import time
led = digitalio.DigitalInOut(D13)
led.direction = digitalio.Direction.OUTPUT

boton = digitalio.DigitalInOut(D0)
boton.switch_to_input(pull = digitalio.Pull.UP)

while True:
    print(str(boton.value))
    led.value = True
    time.sleep(5)
    led.value = False
    time.sleep(5)
    print("Reset")`

```
![image](https://user-images.githubusercontent.com/8715770/51091524-332eb680-1751-11e9-8060-217031342f58.png)

```
![image](https://user-images.githubusercontent.com/8715770/51091532-3e81e200-1751-11e9-96ae-13f486b23edc.png)

**Comment by brentru** [comment]
Hi @Arukaito - I'm not able to reproduce this with a Feather M4 running CircuitPython 3.1.1.

_What version of CircuitPython are you running?_

_Can you comment below with the output of the debugger log from the kernel?_

If you launch Jupyter from the terminal (`jupyter notebook`), you'll see the debug log when starting a new CircuitPython notebook: 

```
DEBUG:circuitpython_kernel.board:connect: open /dev/cu.usbmodem14241
DEBUG:circuitpython_kernel.board:serial already open
DEBUG:circuitpython_kernel.board:* enter raw repl ...
DEBUG:circuitpython_kernel.board:* entered raw repl, returning to kernel...
DEBUG:circuitpython_kernel.kernel:received: OK
DEBUG:circuitpython_kernel.kernel:Output: 'a
```

**Comment by Arukaito** [comment]
This is my Log : `[I 18:34:51.164 LabApp] Kernel restarted: 676dde64-8f69-4718-89d9-327d49f478c3
DEBUG:asyncio:Using selector: SelectSelector
DEBUG:asyncio:Using selector: SelectSelector
DEBUG:circuitpython_kernel.kernel:circuitpython_kernel version 0.3.0.dev
[I 18:34:52.179 LabApp] Adapting to protocol v5.1 for kernel 676dde64-8f69-4718-89d9-327d49f478c3
[I 18:34:52.180 LabApp] Restoring connection for 676dde64-8f69-4718-89d9-327d49f478c3:928b2b38-cb74-499e-b0ae-6498b4b3f2de
[I 18:34:52.181 LabApp] Replaying 3 buffered messages
[I 18:34:52.193 LabApp] Adapting to protocol v5.1 for kernel 676dde64-8f69-4718-89d9-327d49f478c3
DEBUG:circuitpython_kernel.board:COM1
DEBUG:circuitpython_kernel.board:COM3
DEBUG:circuitpython_kernel.board:COM10
DEBUG:circuitpython_kernel.board:CircuitPython Board Found at: COM10
DEBUG:circuitpython_kernel.board:Connected? False
DEBUG:circuitpython_kernel.board:connect: open COM10
DEBUG:circuitpython_kernel.board:serial already open
DEBUG:circuitpython_kernel.board:* enter raw repl ...
DEBUG:circuitpython_kernel.board:* entered raw repl, returning to kernel...
`

Replicated using CircuitPython Kernel version: 0.3.2
Can see the printouts with PUTTY attached. to the COM Serial Port

**Comment by brentru** [comment]
Which version of _CircuitPython_ (not CircuitPython Kernel) are you running on the Metro Express?

**Comment by Arukaito** [comment]
reinstalled Jupyterlab and
Worked fine with Adafruit CircuitPython 4.0.0-alpha.5
Thank you! 
maybe was a wrong installation from my part
