### ISSUE TITLE
Access RTD

### ISSUE THREAD

**Issue by willingc** [adafruit/circuitpython_kernel#3]
Hey @tannewt, I gave you admin/maintainer rights on the circuitpython_kernel docs on RTD if you wish to move it over to Adafruit or add other maintainers.

My code is @ladyada's code ;-)

**Comment by willingc** [comment]
Also happy to transfer the original repo to Adafruit as well if desired.

**Comment by brentru** [comment]
@willingc Could you also add me as an admin and/or maintainer on the RTD docs? Thanks!

**Comment by willingc** [comment]
Added you to RTD @brentru. I'm traveling at the moment but should have some time in the next few days. If you have specific questions, just ask them here as GitHub I check regularly but other social media I shut off when I'm working.

To get you started if you haven't already seen it, this [documentation on making a kernel](http://jupyter-client.readthedocs.io/en/stable/kernels.html) is helpful. This particular kernel is a simple wrapper kernel/echo kernel.

The two key files are board.py (communication from the kernel to the board itself via a serial connection) and kernel.py (which handles communication to/from the notebook using ZeroMQ protocol and forms/decodes the bytestrings used to send/receive info from the board over serial). 

jupyter notebook UI <--0MQ--> kernel <----serial----> board

As for tests, we typically use pytest for jupyterhub and other Jupyter stuff. Looking at the Octave kernel will probably give you some insights on tests which I honestly haven't even thought about.

**Comment by brentru** [comment]
Thank you for the links @willingc! Super useful, and I've added a good amount of changes (planning a release next week for v0.3.0, writing learn guide and a screencast of the kernel). I've been looking at Octave and a bunch of kernels for reference.

Moving forwards, I'm planning to replace board.py with cpboard.py (https://github.com/adafruit/circuitpython/blob/master/tools/cpboard.py) and integrate that with kernel.py.

**Comment by willingc** [comment]
I think that sounds great @brentu. I would like us to add docstrings to any of the python files for maintainability in the future, autodocumentation, and to help with understanding by those interested in the code (learning opportunity).
